Extractor:
  id_globber: "^[0-9A-Z]+"
  pyrad_param_file: "../assets/t2wfs/norm_graph.yml"

Selector:
  criteria_threshold: [0.5,0.5, 0.5]  # Low inclusion criteria to keep the example running fast
  n_trials: 1
  boot_runs: 1
  boot_ratio: [0.8, 1.0]
  thres_percentage: 0.1

